global:
  scrape_interval: 5s  # scrape every 5 seconds

scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets: ['localhost:4040']  # Spark UI

  - job_name: 'kafka_consumer'
    static_configs:
      - targets: ['localhost:7071']  # Your custom Python consumer exporter
