services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ds_project
      MYSQL_USER: ds_user
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      timeout: 300s
      retries: 10

  app:
    build:
      context: .
    environment:
      DB_USER: ds_user
      DB_PASSWORD: userpass
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ds_project
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./database:/app/database
      - ./models:/app/models

volumes:
  mysql_data:
