RUN pip install cryptography


services:

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ds_project
      MYSQL_USER: ds_user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3307"

  app:
    build:
      context: .
    environment:
      DB_USER: ds_user
      DB_PASS: userpass
      DB_HOST: db
      DB_NAME: ds_project
    depends_on:
      - db
environment:
  MYSQL_ROOT_HOST: '%'
